kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: highscore-backup
  namespace: arcade
subjects:
- kind: ServiceAccount
  name: highscore-backup
  namespace: gitops
roleRef:
  kind: Role
  name: highscore-backup
  apiGroup: ""
