apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: s3e
    app.kubernetes.io/component: s3e
    app.kubernetes.io/instance: s3e
  name: s3e
  namespace: arcade2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: s3e
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: s3e
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/arcade2/s3e
        imagePullPolicy: Always
        name: s3e
        ports:
        - containerPort: 8080
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30