apiVersion: v1
imagePullSecrets:
- name: proxy-dockercfg-2k2pj
kind: ServiceAccount
metadata:
  name: proxy
  namespace: arcade
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"platform-proxy"}}'

secrets:
- name: proxy-token-bkcbt
- name: proxy-dockercfg-2k2pj
